### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by aitjcize** [aitjcize/PyTox#40]
First of all, I don't know why-tf the previous post got removed. I'll have to ask Github what is happening.

Here is the content from the original post:

I don't know if this is the correct place to ask this, but I don't know what other ways to contact you and this is a very serious issue with the Tox project. irungentoo deleted these concerns from the toxcore repository, so this I have to bring it up here instead. irungentoo is enforcing censorship on this. I hope you don't censor these concerns as other members of the Tox Foundation are doing.

Recently @Proplex left the project over the following discussion: https://gist.github.com/irungentoo/5af26f5edefcdb7eac72

Soon after, I came to the following intriguing link: https://mail.tox.im/prolapse.txt

Can you explain why the Tox Foundation is tracking when Proplex visits your websites?
For an organization that says it is privacy-respecting, freedom lover and whatnot, this is highly contradictory and raise many concerns.

PS: sorry if this isn't the right repository, but this issue really needs to be discussed and it is relevant to the Tox project as a whole.

EDIT:
Red alert: The document of https://mail.tox.im/prolapse.txt has been edited. Really looks like someone from the Tox Foundation is trying to cover this up. Hopefully the service archive.today let us see what was previously hosted on the website.
https://archive.today/KkSWp

--

https://gist.github.com/urras/ba792274f5aaf662a082

**Comment by ReAzem** [comment]
All posts were removed at the same time on all repos.

**Comment by aitjcize** [comment]
I think it's the repo owner's right to determine whether to remove it or not. It's very wrong that github just remove the issue like that.

**Comment by iphydf** [comment]
Is this still an issue?

**Comment by kitech** [comment]
I don't sure. Only one link show that, web server log saved somewhere: https://archive.today/KkSWp

**Comment by GrayHatter** [comment]
the post was removed because it was a troll who was trying to flamebate a response, and spreading FUD. Concern trolls are the flavor of choice on github. Nothing more to see here.

Asking if this is still an issue is the nice way of suggesting you not feed the troll, and close this issue. As it has NOTHING to do with pytox. So it only serves as a false flag, meant to give anyone who reads a negative connotation of tox.

**Comment by kitech** [comment]
Close this issue. As it has NOTHING to do with pytox.
