### ISSUE TITLE
Tox API update

### ISSUE THREAD

**Issue by nurupo** [aitjcize/PyTox#42]
Toxcore is [in the process of updating its API](https://github.com/irungentoo/toxcore/tree/new_api) (check the public headers), which would break the bindings. Just a heads up.

**Comment by rysiekpl** [comment]
This is highly relevant to my interests.

**Comment by aitjcize** [comment]
@rysiekpl feel free to work on it and send PRs :)

**Comment by rysiekpl** [comment]
@aitjcize now, if I only knew C well enough... currently working on a hobby project that uses PyTox, which also eats up all my free time. But if you need a tester, I'm in.

**Comment by gak** [comment]
Is anyone working on this? @irungentoo is about to merge the new API to master, according to http://www.reddit.com/r/projecttox/comments/2zerds/the_new_core_api_is_fully_implemented_and_almost/

I want to contribute, but don't have the spare time at the moment.

**Comment by aitjcize** [comment]
I'm currently very busy on my work now, so if anyone could help I'll be much appreciated.

**Comment by rysiekpl** [comment]
There seems to be a new API compatible fork of PyTox: https://github.com/abbat/pytoxcore/

**Comment by kitech** [comment]
newapi update now: https://github.com/aitjcize/PyTox/pull/45

**Comment by mrshu** [comment]
@kitech this can be closed now, right?

**Comment by kitech** [comment]
yes, the newapi has merge to  main repo's master, can closed now.
