### ISSUE TITLE
about toxcore old api in current master

### ISSUE THREAD

**Issue by kitech** [aitjcize/PyTox#48]
maybe now branch current master to oldapi. 
toxcore has updated and improved a lots from master's last update.

**Comment by aitjcize** [comment]
Hi Kitech,

I currently don't have time to maintain this project anymore.
I saw the PR you sent and it looks generally good to me.
Let me give you commit access so you can continue to work on it.

**Comment by kitech** [comment]
OK, thanks. 
I can do some work on pytox recently.
