### ISSUE TITLE
Python aborts when friend comes online using Antidote client

### ISSUE THREAD

**Issue by aserranoh** [aitjcize/PyTox#62]
When a friend comes online using the Android Antidote client, it sends a file of type TOX_FILE_KIND_AVATAR, but with filename = NULL and filename_length = 0. Then, the assertion in the file core.c line 141:

assert(TOX_HASH_LENGTH == filename_length);

fails, and python aborts. Isn't that assertion restricting cases that the tox protocol accepts?

**Comment by GrayHatter** [comment]
That assert is incorrect; an avatar with file size 0 means avatar deleted. (or never existed)

**Comment by kitech** [comment]
Oh， thanks
