### ISSUE TITLE
Arm not support？

### ISSUE THREAD

**Issue by tetsaicn** [aitjcize/PyTox#63]
gcc 4.9.2
Python 2.7
toxcore is installed.

**Comment by kitech** [comment]
arm is supported.

paste your install info.

**Comment by kitech** [comment]
python setup.py install

**Comment by tetsaicn** [comment]
嗯可以的，既然你是中国人就说中文吧，英语费劲。
目前安装是成功了，但是为什么收不到on_group_invite的回调，参数名字我都原样复制都没用，其他回调正常。

**Comment by tetsaicn** [comment]
具体现象为空，根本没有调用过的迹象，无论是在回调下面加上加入群组，还是直接print一个消息出来，都没有任何反应

**Comment by tetsaicn** [comment]
记得更新文档老铁，不然没法用
