### ISSUE TITLE
Alternative wrapping for Python available

### ISSUE THREAD

**Issue by emdee-is** [aitjcize/PyTox#69]
This seems to be abandoned and the successor in TokTok/py-toxcore-c does not have much coverage yet.

There is an alternative in https://git.plastiras.org/emdee/tox_profile/ that uses CTYPES and has good coverage, including NGC groups and toxencryptsave,

Hopefully the excellent test suite here can be ported to it.

**Comment by aitjcize** [comment]
Will update README.md, thanks.
